spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.3.169:3306/asset_warehouse?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: asset_warehouse
    password: asset_warehouse
    # 连接池配置 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    druid:
      initial-size: 10
      min-idle: 10
      max-active: 50
      max-wait: 60000
      # druid 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      # druid 验证数据库连接的有效性
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: false
      test-on-return: false
      test-on-borrow: false
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # druid 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      # druid 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,slf4j
      #      aop-patterns: "com.springboot.template.dao.*"
      # 参数可以在 com.alibaba.druid.spring.boot.autoconfigure.properties.DruidStatProperties 中找到
      filter:
        wall:
          # 开启防火墙
          enabled: true
          config:
            # 允许执行批处理
            multi-statement-allow: true
            # 不允许执行删除
            delete-allow: false
        # druid 状态监控
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000 # 慢SQL记录
          merge-sql: true # mergeSql功能
        # 日志监控，使用slf4j 进行日志输出
        slf4j:
          enabled: true
          statement-log-error-enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      # druid 监控过滤器
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*'
        # 开启session统计功能
        session-stat-enable: true
        # session的最大个数,默认100
        session-stat-max-count: 1000
      # druid 监控页面
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        reset-enable: false
        # 允许访问的地址，如果allow没有配置或者为空，则允许所有访问
        # allow: 127.0.0.1
        # 拒绝访问的地址，deny优先于allow，如果在deny列表中，就算在allow列表中，也会被拒绝
        # deny: